name: xai_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.23.5
  - pandas=2.2.3
  - matplotlib=3.7.1
  - scikit-learn
  - shap=0.46.0
  - lime=0.2.0.1
  - streamlit=1.40.0
  - pip
  - pip:
      - fastapi==0.97.0
      - uvicorn==0.22.0
      - h5py==3.8.0
      - onnxruntime
      - captum==0.7.0
      - onnx2torch
      - torchinfo==1.8.0
      - torchvision==0.15.2
      - torchviz==0.0.2
      - xgboost==2.1.2
      - graphviz==0.20.3
